### ISSUE TITLE
GetNetworkStats produces invalid Utf8 strings and panics

### ISSUE THREAD

**Issue by ZantetsukenGT** [Sreyas-Sreelal/omprs-gdk#1]
Calling GetNetworkStats, produces a panic:

```rs
    fn on_player_update(&mut self, player: Player, _now: isize) -> bool {
        let mut output_string = String::with_capacity(500);

        GetNetworkStats(&mut output_string);

        //player.show_dialog(0, DialogStyle::MsgBox, "test", &output_string, "Ok", "");
    }
```

The stacktrace seems to be a little bit broken too
```
thread '<unnamed>' panicked at C:\...\omp-gdk-0.2.0\src\types\stringview.rs:25:18:
called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0, error_len: Some(1) }
stack backtrace:
   0: 0x7170ce5a - OMPRS_onPlayerClickGangZone
```

Been toying with this a bit, congrats on delivering this very interesting project 👌

**Comment by Sreyas-Sreelal** [comment]
The issue seems  to be in the component (more precisely [here](https://github.com/Sreyas-Sreelal/omprs/blob/5a7861bf6354a1ef1b1c7e3a3eda926616f36895/functions/utils.hpp#L384)) , where I'm copying the string, which is scope allocated and dangerous. I may have to rewrite and re approach every native related to network stats. Just one native `GetNetWorkStats` returning `NetworkStat` struct would be enough.

Also thank you for taking your time to test this project :).
